### ISSUE TITLE
Failed to install; Error while parsing

### ISSUE THREAD

**Issue by aquaritus** [B3nac/InjuredAndroid#1]
I wanted to try out your App. Unfortunately an error occured, while I tried to install the app via adb.
The Phone I use is a Samsung Galaxy S6.

MD5Hash of the apk: c0791ea520cdf0b1879deec50ed267fe  InjuredAndroid.apk

Error Message:
Failed to install InjuredAndroid.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl959478977.tmp/base.apk: AndroidManifest.xml]

**Comment by B3nac** [comment]
Not sure why I didn't see this sooner. I'm going to upload a new apk soon with more flags. Please test that one out.

**Comment by B3nac** [comment]
Hi @aquaritus let me know if the new apk installs correctly. I just successfully installed it on my Galaxy S7.

**Comment by B3nac** [comment]
Fixed in newest release.
