### ISSUE TITLE
RCEActivity won't work w/ Android >= 10 (Q)

### ISSUE THREAD

**Issue by BinaryKhaos** [B3nac/InjuredAndroid#10]
Executing files in the App's home directory no longer works w/ Android >= 10 and is denied by SELinux. A workaround is to package the binaries into the native libs directory (w/ "android:extractNativeLibs=true" in the Manifest).

See:
https://issuetracker.google.com/issues/128554619

**Comment by B3nac** [comment]
Thanks for letting me know! Interesting, shouldn't need too much of a modification to the exercise then. I think the binaries for the exercise are already in the /libs directory, so it looks like I only need to add `android:extractNativeLibs=true` to the manifest.
