### ISSUE TITLE
Flutter module missing x86_64 library

### ISSUE THREAD

**Issue by BinaryKhaos** [B3nac/InjuredAndroid#11]
Even though Flutter supports x86_64 on Android since ~2019, the APK is missing the respective native library and as such, the Activity crashes with a dlopen error on such an architecture (e.g. while running on an emulator).

**Comment by B3nac** [comment]
Thanks for letting me know! I'll test this out on an x86_64 emulator. I believe there's an entry that needs to be added to the gradle build.config.

**Comment by B3nac** [comment]
Hi! I think I fixed this by specifically including the x86_64 library. Please let me know if the fix worked by testing the latest release, thank you!

```
ndk {
                // Filter for architectures supported by Flutter.
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
            }
```

**Comment by B3nac** [comment]
Closed issue as fixed.
