### ISSUE TITLE
Level 8 - error with AWS

### ISSUE THREAD

**Issue by fabioleanti** [B3nac/InjuredAndroid#12]
i'm trying to retrieve data from s3 but when i run:
`aws s3 ls`
I receive this:
`An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`
I'm missing something or this level is broken?

**Comment by B3nac** [comment]
Hi @fabioleanti thank you for bringing this to my attention. Looks like the bucket permissions were reset, I just made the s3 bucket public again. This cli command should work `aws s3 ls s3://injuredandroid` and the web endpoint for sure works `https://injuredandroid.s3.us-west-1.amazonaws.com/`. Please let me know if there's still issues with the cli command, thanks again!

**Comment by fabioleanti** [comment]
unfortunatly it doesn't work, the web endpoint works @B3nac  maybe [this](https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-denied-listobjects-sync/?nc1=h_ls) might help you, let me know!

**Comment by B3nac** [comment]
Hi @fabioleanti! I added a bucket policy that hopefully should fix this issue. If not I should be able to fix this tomorrow.

**Comment by B3nac** [comment]
Confirmed this is working again as intended. Example command `aws s3 ls s3://injuredandroid --no-sign-request`.
