### ISSUE TITLE
Flag - 8 Not solvable

### ISSUE THREAD

**Issue by nandy6666** [B3nac/InjuredAndroid#14]
aws s3 ls s3://injuredandroid --profile injuredandroid

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Comment by nandy6666** [comment]
Even submitting the flag value (C10ud_S3cur1ty_lol) from the walkthroughs, it's not getting submitted.

**Comment by m00nbyt3** [comment]
Same here

**Comment by B3nac** [comment]
Hi @nandy6666 @m00nbyt3 there needs to be a profile setup called injuredandroid for that command to work. Use this command if a profile isn't setup.

`aws s3 ls s3://injuredandroid --no-sign-request`
