### ISSUE TITLE
secret url showing not found actually ....!

### ISSUE THREAD

**Issue by balook** [B3nac/InjuredAndroid#3]
I tried to access this url ...secret_url...  but showing not found it was aquired after decoding an remote url in the apk pls check it

**Comment by superhero1** [comment]
@balook can you please remove the url here? just leave it as ...39... or something

**Comment by B3nac** [comment]
Hi all, I'm going to update this url in the next release after VirSecCon2020.

**Comment by B3nac** [comment]
This is fixed with the latest update.
