### ISSUE TITLE
Flag 7 being completed with 8

### ISSUE THREAD

**Issue by bmt626** [B3nac/InjuredAndroid#4]
I was working through the ctf and got stuck on flag 7 so moved on to flag 8 and noticed that completing that flag also marks flag 7 as completed.

**Comment by B3nac** [comment]
Thank you for reporting this @bmt626 . What caused it was a mistake with the button logic.

```java
if (settings.getBoolean("flagEightButtonColor", false)) {
            flagEightButtonColor = settings.getBoolean("flagEightButtonColor", true);
            flagSevenButton.getBackground().setColorFilter(Color.GREEN, PorterDuff.Mode.SRC_ATOP);
        }
```
Flag seven was being changed to green inside of the flag eight overview if statement. This is fixed with the latest build.
