### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by sillydadddy** [B3nac/InjuredAndroid#6]
Hi B3nac
I am getting the following error while installing the apk 
adb install InjuredAndroid.apk
Performing Streamed Install
adb: failed to install InjuredAndroid.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1870249613.tmp/base.apk: AndroidManifest.xml]

I am using AVD Android 8.1 x86

thanks
siLLyDaddy

**Comment by B3nac** [comment]
Hi @sillydadddy what happens when dragging and dropping the InjuredAndroid.apk into the Android 8.1 x86 emulator? I was able to successfully install with this method.

**Comment by B3nac** [comment]
Let me know if this error still exists with the latest build and I will try to track down the error.
