### ISSUE TITLE
Issue in FLAG 9 submission

### ISSUE THREAD

**Issue by mzfr** [B3nac/InjuredAndroid#8]
I was able to find the json path and it returns `[nine!_flag]` but that doesn't work in the app.

![image](https://user-images.githubusercontent.com/16623935/84568727-06942980-ad9f-11ea-9f70-39710bc325af.png)

![Screenshot_20200613-175246](https://user-images.githubusercontent.com/16623935/84568733-10b62800-ad9f-11ea-84f2-614ef3db73d5.png)

Is this the correct flag or am I on wrong path?

**Comment by B3nac** [comment]
Hi @mzfr there's one more step needed before submitting. `decoded.equals(value)` :)
