### ISSUE TITLE
getting error while building the project in android studio ... flutter module giving a lot of trouble while building ..!

### ISSUE THREAD

**Issue by balook** [B3nac/InjuredAndroid#9]
# I tried to build the apk injured android ...installed all dependies flutter sdk and dart sdk after that this error were raising 

Task :flutter:compileFlutterBuildDebug
Target kernel_snapshot failed: FileSystemException: Cannot open file, path = 'D:\android\build\flutter_module\.packages' (OS Error: Access is denied.
, errno = 5)
build failed.

**Comment by balook** [comment]
* Mainly Flutter module error most of the time... i have setup in right directory everything

**Comment by B3nac** [comment]
What OS are you using when trying to compile the Flutter module? Access denied looks like possibly sudo is needed, I don't think I needed sudo to build the module though. I need more info in order to help as this issue depends on the OS and build setup. Might have more luck adding a Flutter module and replacing the dart files with the exercise dart code. Running `flutter doctor` might help resolve the issues as well.

**Comment by balook** [comment]
I'm using windows ...I'm also got error like .packages not found in the modules directory ..I added manually .packages......folder...after that got error like permission denied .....! 
## My is win64 10

**Comment by balook** [comment]
Executing tasks: [:app:assembleDebug] in project D:\android\build\InjuredAndroid


> Configure project :app
Kotlin plugin should be enabled before 'kotlin-android-extensions'

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE

> Task :flutter:compileFlutterBuildDebug FAILED
Target kernel_snapshot failed: FileSystemException: Cannot open file, path = 'D:\android\build\flutter_module\.packages' (OS Error: The system cannot find the file specified.
, errno = 2)
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter_windows_1.17.4-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':flutter:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter_windows_1.17.4-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

**Comment by balook** [comment]
i tried doctor app running fine and also i created a app with flutter default app its also working fine ..but injured andorid was gving error

**Comment by B3nac** [comment]
I'm guessing there's some build files missing for the flutter module that were taken out by the official .gitignore. Try building the source for the InjuredAndroid Flutter module with the default app you created and see if it compiles successfully. Unfortunately I use Ubuntu as my development machine so I'm not sure what is causing the permissions error on Windows 10. 

> I'm using windows ...I'm also got error like .packages not found in the modules directory ..I added manually .packages......folder...after that got error like permission denied .....!
> 
> ## My is win64 10

Are the files above the user level directory? This path `D:\android\build\flutter_module.packages` looks like Administrator permissions are needed. Try building in a user level path.

**Comment by B3nac** [comment]
I'm planning on re-downloading the project source to see if .gitignore is excluding a needed file to build the flutter module. Stay tuned!

**Comment by B3nac** [comment]
Recently rebuilt InjuredAndroid successfully on Windows and I believe this error may have resulted from the local.properties not linking the Flutter SDK and Android SDK.

This file "local.properties" has to be created because everyone's SDK paths are different.

Contents of local.properties example for Windows:

```
sdk.dir=C:\\Users\\B3nac\\AppData\\Local\\Android\\Sdk
flutter.dir=C:\\Users\\YourUsername\\PathTo\\flutter
```

**Comment by B3nac** [comment]
Hi @balook I found the real cause of the non zero exit code.

Not setting the path additionally in Android Studio is the main cause of this error. Here's the steps I took to solve this issue.

1. Set the Flutter path in Android Studio

File -> Settings -> Languages ​​& Frameworks -> Flutter

2. Enable Dart Support

3. Run `flutter pub get` to import the flutter dependencies
